# Required ENV variables
# DOCKER_USER, DOCKER_PASS
version: 2.1
aliases:
  - &parameters
    alpine_version:
      default: latest
      type: string
    repo:
      default: drpsychick
      type: string
    tag:
      default: latest
      type: string
  - &docker-dind
    - image: docker:dind
  - &build
    - checkout
    - setup_remote_docker:
        version: 20.10.14
    - run:
        # plain docker build x86 without cross-platform
        name: Build images
        command: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin &> /dev/null || exit 1
          export img=texlive-pdflatex
          export TAG=<< parameters.alpine_version >>
          VERSION=<< parameters.alpine_version >>
          echo "Building << parameters.repo >>/$img:$TAG based on $VERSION"
          docker build --progress plain \
            --build-arg ALPINE_VERSION=<< parameters.alpine_version >> \
            --tag << parameters.repo >>/$img:$TAG .
    - run:
        name: Test images
        command: |
          export img=texlive-pdflatex
          export TAG=<< parameters.alpine_version >>
          export VERSION=$(docker run --rm << parameters.repo >>/$img:$TAG pdflatex -version |awk '$1 == "pdfTeX" { print $2; exit }' |awk -F- '{print $3}')
          echo "Alpine $TAG pdfTeX $VERSION"
          echo "Running tests...";
          docker run --rm --name pdflatex << parameters.repo >>/$img:$TAG pdflatex -version
          # dummy container for example files
          docker create -v /data --name example busybox /bin/true
          docker cp example/loreipsum.tex example:/data
          # generate PDF and thumbnails
          docker run --rm --volumes-from example << parameters.repo >>/$img:$TAG pdflatex /data/loreipsum.tex
          docker run --rm --volumes-from example << parameters.repo >>/$img:$TAG sh -c 'thumbpdf /data/loreipsum.pdf'
          docker run --rm --volumes-from example << parameters.repo >>/$img:$TAG pdflatex /data/loreipsum.tex
    - run:
        name: Push images
        command: |
          export img=texlive-pdflatex
          export TAG=<< parameters.alpine_version >>
          docker push << parameters.repo >>/$img:$TAG

jobs:
  build:
    parameters: *parameters
    docker: *docker-dind
    resource_class: small
    steps: *build

workflows:
  version: 2
  build-images:
    jobs:
      - build:
          matrix:
            parameters:
              alpine_version: ["alpine-3.16", "alpine-3.17", "latest"]

  # build other tags monthly
  monthly:
    triggers:
      - schedule:
          # first day of month, 5:03 am, UTC
          cron: "3 5 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          matrix:
            parameters:
              alpine_version: ["alpine-3.16", "alpine-3.17", "latest"]
